name: drift_db_inspector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  file_picker: ^8.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.3.1
  hugeicons: ^1.1.6
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: "assets/fonts/PlusJakartaSans[wght].ttf"
        - asset: "assets/fonts/PlusJakartaSans-Italic[wght].ttf"
          style: italic
